include:
  - board: seeeduino_xiao_ble
    shield: totem_left
  - board: seeeduino_xiao_ble
    shield: totem_right
# there is no settingsreset (needed) for the XIAO
# Reset Firmware(https://zmk.dev/docs/troubleshooting/connection-issues)
# include:
#   - board: seeeduino_xiao_ble
#     shield: totem_left
#   - board: seeeduino_xiao_ble
#     shield: totem_right
#   - board: seeeduino_xiao_ble
#     shield: settings_reset
